name: tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        platform: [ubuntu-latest]

    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Setup Go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version-file: go.mod
          cache: false

      - name: Lint
        uses: golangci/golangci-lint-action@ba0d7d2ec06a0ea1cb5fa41b2e4a3ab91d21278a # v9.3.0
        with:
          version: v2.12

      - name: Tests
        run: |
          make test

      - name: Train BPE Tokenizer
        run: |
          make dl
          make tokenize

      - name: Pre-Train GPT
        run: |
          go run ./cmd/pretrain/main.go --context-len 32 --embed-dim 24 --batch-size 4 --max-iters 5
          cat loss.csv

      - name: Generate Text
        run: |
          go run ./cmd/generate/main.go --max-new-tokens 32
